# Full reference https://github.com/foundry-rs/foundry/tree/master/config

[profile.default]
evm_version = 'cancun'
bytecode_hash = "none"
fuzz = { runs = 256 }
gas_reports = ["*"]
libs = ["lib"]
optimizer = true
optimizer_runs = 10_000
out = "out"
solc = "0.8.28"
src = "src"
test = "test"

[profile.ci]
fuzz = { runs = 1_000 }
verbosity = 4
